### ISSUE TITLE
Pip issue in kern-2.def

### ISSUE THREAD

**Issue by aminiussi** [AfricanResearchCloud/idia-containers#15]
Hi,
It seems a `-y` is missing in kern-2.def
```
diff --git a/kern2/kern-2.def b/kern2/kern-2.def
index 6f23e02..0665f49 100644
--- a/kern2/kern-2.def
+++ b/kern2/kern-2.def
@@ -23,7 +23,7 @@ Include: software-properties-common
         rm /var/lib/dpkg/info/texlive-fonts-recommended.list 
 
        # Install pip and ipykernel for use with jupyter hub. 
-       apt-get install python-pip
+       apt-get install -y python-pip
        pip install ipykernel
 
        # Additional packages installed via pip can be added here.
```

Also, once that issue fixed, the singularity build fails with:
```
+ pip install ipykernel
Collecting ipykernel
  Downloading https://files.pythonhosted.org/packages/c1/43/a7c6398e3ca3748781f7cd13c1b0d17725ee5bd3c1df39a3e8d66341ca3a/ipykernel-5.2.1.tar.gz (106kB)
    100% |################################| 112kB 1.7MB/s 
    Complete output from command python setup.py egg_info:
    ERROR: ipykernel requires Python version 3.5 or above.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-W8REhf/ipykernel/
```

Is this def file up tp date ?

Thanks

**Comment by daikema** [comment]
Hi.  This repo hasn't been updated in several years and https://kernsuite.info/installation/ describes kern-2 as past end of life and no longer supported.  Python 2 was also been declared to have reached it's end of life as of Jan 1, 2020, so I suspect that you may have problems installing certain versions of some packages if you're attempting to use it (though archived versions may still be available).

If you do need an updated def there is one at https://github.com/idia-astro/idia-container-kern and https://github.com/kernsuite/singularity also include a def file (but much newer).
