### ISSUE TITLE
Easy Way to List Package Contents?

### ISSUE THREAD

**Issue by foxmouldy** [AfricanResearchCloud/idia-containers#2]
Is there any easy way for us to list the contents of a container? 

That way, we could simply ask people to check the contents first, and then open an issue if the relevant software hasn't been installed in container.

What do you think?

**Comment by Shadowphax** [comment]
This is a good idea. As a start I would suggest that we apply a README.md to each container area in git and update the software list there.

**Comment by daikema** [comment]
How comprehensive should this be?  A README might be advisable, but it seems to me that those can fall behind the actual contents of the containers.

Maybe README + a list from dpkg of the packages installed (and versions thereof)?

**Comment by foxmouldy** [comment]
Right now I'm just looking at the `def` file. Perhaps we ought to write a small script that greps this from the def file and pops it into the README?

**Comment by Shadowphax** [comment]
I have updated the kern2.img . Let me know if this works for you guys. Executing "./kern2.img " will list the available python modules. I have not included any binary options. Let me know if this is okay. Also a brief usage example attached.  

        echo "The following Python modules is installed in this image:"
        echo "Example usage: singularity.img [command] [args] [options]" 

37b726f..b8a85bf  master -> master

**Comment by daikema** [comment]
"modules is"  <- grammar

(edit: and is that line repeated twice in the committed version?)

**Comment by Shadowphax** [comment]
Updated grammatical error 
  c158781..1023503  master -> master

**Comment by foxmouldy** [comment]
Yeah that looks good.
