### ISSUE TITLE
Add PYBDSF to Kern-2

### ISSUE THREAD

**Issue by foxmouldy** [AfricanResearchCloud/idia-containers#3]
Could we add the following software to the KERN-2 Container?
http://www.astron.nl/citt/pybdsm/

It ought to be available via the Kern-2 repo.

**Comment by daikema** [comment]
Think this is part of the lofar package which @Shadowphax said something about errors during the install.

**Comment by foxmouldy** [comment]
But its not really part of the LOFAR package:
https://github.com/lofar-astron/PyBDSF

**Comment by daikema** [comment]
Maybe a difference between how LOFAR has things classified in github and how kern is being built?  e.g. if I look at https://launchpad.net/~kernsuite/+archive/ubuntu/kern-2/+packages - and download [the blob that the lofar set of packages is constructed from](https://launchpad.net/~kernsuite/+archive/ubuntu/kern-2/+files/lofar_2.20.2.orig.tar.bz2), it seems that PyBSDM is there.  (I haven't tracked down which of the resulting files it winds up in).

**Comment by Shadowphax** [comment]
So lofar and meqtrees are installed. These two packages in question was the real reason why I needed to split the installation sequence. So should PYBDSF exist as part of Lofar ?

**Comment by daikema** [comment]
Looks like the bdsm python module is in there but you have to manually set the PYTHONPATH at the moment:

```
$ python
Python 2.7.11+ (default, Apr 17 2016, 14:00:29) 
[GCC 5.3.1 20160413] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import bdsm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named bdsm
>>> quit()
$ export PYTHONPATH=/usr/lib/python2.7/dist-packages/lofar
$ python
Python 2.7.11+ (default, Apr 17 2016, 14:00:29) 
[GCC 5.3.1 20160413] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import bdsm
/usr/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
```

I haven't found a pybdsm / pybdsf binary anywhere which I think @foxmouldy may is looking for - or is the python package enough?

**Comment by Shadowphax** [comment]
@foxmouldy , do you need the binaries as well ?

**Comment by foxmouldy** [comment]
@Shadowphax No, as per our discussion, and **pybdsm** seems to be working okay. I'm going to close this issue.
