### ISSUE TITLE
source finding container dead

### ISSUE THREAD

**Issue by arusstaylor** [AfricanResearchCloud/idia-containers#6]
Keep getting a dead kernel message when trying to run a notebook with the source finding kernel.

**Comment by foxmouldy** [comment]
User chooses the "Source Finding" container from the Jupyter-Hub. Kernel fails to start from scratch and when "restart" is attempted. Could be an issue in the configuration. Screenshots attached.

![screen shot 2017-08-10 at 12 34 30](https://user-images.githubusercontent.com/1917908/29166536-07bb4a7e-7dc7-11e7-97a8-f40a14c57918.png)
![screen shot 2017-08-10 at 12 33 21](https://user-images.githubusercontent.com/1917908/29166537-08016022-7dc7-11e7-8f37-e046dfdb6700.png)

**Comment by Shadowphax** [comment]
The runscripts for a container are usually executed when a container is queried. In the case of the source-finding singularity container, the lisst of installed software is executed. I then had to explicitly mentioned in the kernel.json of the Jupyter hub to execute python.  

` "display_name": "Source Finding", 
 "language": "python", 
 "argv": [
  "/data/exp_soft/containers/source-finding.img", 
  "python",
  "-m", 
  "ipykernel_launcher", 
  "-f", 
  "{connection_file}"
 ]
}
`
