### ISSUE TITLE
KERN-2 Container: Rebuild with new KATDAL and KATPOINT

### ISSUE THREAD

**Issue by foxmouldy** [AfricanResearchCloud/idia-containers#7]
Assigned to: @Shadowphax 
KERN-2 Container needs to be rebuilt as follows:
Don't build katdal or katpoint using KERN-2, but use pip install. Here's the comments from Ludwig Shwartz, the code maintainer:

> Please update to katdal 0.8 (via pip install) or the master branch here on github. That in turn needs the latest katpoint (0.7), just to be sure.

**Comment by Shadowphax** [comment]
Container has been updated with the latest version of Katdal and Katpoint. I have also updated the rest of the python modules to their latest versions. Closing issue.
