### ISSUE TITLE
KERN-2 and `h5toms.py`

### ISSUE THREAD

**Issue by foxmouldy** [AfricanResearchCloud/idia-containers#8]
KERN-2 has correctly been updated, but the _old_ and _bad_ version of `h5toms.py` is still in `/usr/bin/`, while the _new_ and _good_ version (from **KATDAL 0.8**) is in `/usr/local/bin`, which is lower in KERN-2's `$PATH`. 

Therefore, KERN-2 has to be updated so that the new version of `h5toms.py` sits in `/usr/bin`.

**Comment by Shadowphax** [comment]
I've updated the PATHS preference instead of coping files around. Please confirm and close issue.

**Comment by foxmouldy** [comment]
That’s fine, but why do we have an old h5toms.py script? I’d prefer for the old version to be removed altogether, to prevent the possibility of confusion.

**Comment by Shadowphax** [comment]
It seems the developer has not removed the old script and has therefore used /usr/local/bin instead. I can remove this manually in the container but the developer should clean this up.
